### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by jameskbride** [jameshollingshead/BartenderApp#1]
This project is missing a .gitignore file.  Binary and workstation-specific config files should be removed from the source tree and and excluded.

You might want to consider the following contents for you gitignore:
.gradle
/local.properties
/release.properties
.idea
.DS_Store
/build
*.iml
*.ipr
*.orig

**Comment by jameshollingshead** [comment]
gitignore added. That should fix the issue.

**Comment by jameskbride** [comment]
You'll need to delete these resources out of the repo as well.
